[platformio]
default_envs = uno_r4_wifi

[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
monitor_speed = 115200

lib_deps =
  knolleary/PubSubClient @ ^2.8
  bblanchon/ArduinoJson @ ^7.2

build_flags =
  -DCORE_DEBUG_LEVEL=3

[env:uno_r4_wifi_release]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
monitor_speed = 115200

lib_deps =
  knolleary/PubSubClient @ ^2.8
  bblanchon/ArduinoJson @ ^7.2

build_flags =
  -DNDEBUG
